### ISSUE TITLE
Dynamic Geometry Example  requires source file vector_functions.h

### ISSUE THREAD

**Issue by LyceanEM** [mortacious/python-optix#4]
Trying the new dynamic materials and geometry examples, and the materials one works well. However the dynamic geometry example fails with error message 

`CompileException: /home/timtitan/Documents/10-19-Research-Projects/14-Electromagnetics-Modelling/14.04 Python Development/python-optix/examples/cuda/vec_math.h(43): catastrophic error: cannot open source file "vector_functions.h"`

Looking at the code in vec_math.h it calls for vector types and vector functions. Neither is present in the examples/cuda folder along with vec_math.h

**Comment by mortacious** [comment]
The file `vector_functions.h` is part of the CUDA installation. Make sure, that you have installed CUDA correctly on your system. 

Note: If you are using a `conda` environment you'll have to install `cudatoolkit-dev` instead of `cudatoolkit` for the headers.

**Comment by LyceanEM** [comment]
Well installing cudatoolkit-dev solved the problem instantly. Thank you very much. For working with this code, should I be looking to follow the optix c++ examples to get used to python-optix?

**Comment by mortacious** [comment]
Python-optix strives to be as similar as possible to the original optix API, while also being pythonic. The original API, especially the functions, is therefore not implemented exactly. However, the constants and necessary parameters for the individual objects (c-structs in the original API) are largely the same and only adapted to the Python naming scheme (e.g. `CompileDebugLevel.FULL` instead of `OPTIX_COMPILE_DEBUG_LEVEL_FULL`). 

Therefore Ressources like the [Programming Guide](https://raytracing-docs.nvidia.com/optix7/guide/index.html) are still very useful.

Regarding the C++ SDK examples, some have already been ported to python-optix. Most of the changes between C++ and Python should be clear in them by now. Therefore, the C++ examples can definitely also contribute to the understanding.

**Comment by LyceanEM** [comment]
Right thanks very much. I appreciate all the great work you have put into this.
